global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka'
    static_configs:
      - targets: ['eureka:8761']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
