server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**, /api/v1/company-info/**, /api/v1/shipping-info/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://10.0.1.110:3000, http://10.0.1.110:3001, http://10.0.1.110:3002, http://localhost:3000, http://localhost:3001, http://localhost:3002"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
  discovery:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} - %msg%n"