#################
# APP PROPERTIES
#################

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:3002}

###########################
# SPRING RELATED PROPERTIES
###########################

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**, /api/v1/company-info/**, /api/v1/shipping-info/**
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/v1/categories/**, /api/v1/products/**,
        - id: search-service
          uri: http://search-service:8083
          predicates:
            - Path=/api/v1/cache/products/**
  discovery:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health, info"
  endpoint:
    gateway:
      access: unrestricted
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} - %msg%n"