#################
# APP PROPERTIES
#################

product:
  sync-enabled: true
  scheduled-sync-enabled: true
  sync-interval: 1h

###########################
# SPRING RELATED PROPERTIES
###########################

server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:

  application:
    name: search-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health, info"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} - %msg%n"
