### 1️⃣ Register
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "email": "test@example.com",
  "firstName": "John",
  "lastName": "Doe",
  "password": "securepassword",
  "gender": "UNKNOWN",
  "accountType": "USER"
}

### 2️⃣ Login
# @name login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "securepassword"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### 3️⃣ Get user
GET http://localhost:8080/api/v1/users/1
Authorization: Bearer {{accessToken}}

### 4️⃣ Refresh token
# @name refresh
POST http://localhost:8080/api/v1/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
%}
