name: Publish Contract Product Library

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Maven & GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle
        working-directory: contract-product
        run: chmod +x gradlew

      - name: Run tests for Auth Library
        working-directory: contract-product
        run: ./gradlew build test

      - name: Publish to local Maven (for other jobs)
        working-directory: contract-product
        run: ./gradlew publishToMavenLocal

      - name: Publish to GitHub Packages
        working-directory: contract-product
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}